"""
Unit tests for render_analyzer.py using pytest and Playwright.

Tests all 30 scenarios specified in the requirements deterministically.
"""

from __future__ import annotations

import asyncio
import pytest
from playwright.async_api import async_playwright

from render_analyzer import (
    analyze_rendered_page,
    parse_rendered_dom_structure,
)


@pytest.mark.asyncio
async def test_1_basic_static_html():
    """1. Test basic static HTML rendering."""
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        context = await browser.new_context()
        page = await context.new_page()

        html = "<html><head><title>Static Page</title></head><body><h1>Hello Static</h1><p>Welcome to static page</p></body></html>"
        await page.route("https://example.com/test", lambda route: route.fulfill(status=200, body=html, content_type="text/html"))

        res = await analyze_rendered_page("https://example.com/test", options={"wait_after_load_ms": 0}, page_instance=page)
        await context.close()
        await browser.close()

    assert res["rendering"]["status"] == "success"
    assert res["title"]["value"] == "Static Page"
    assert res["headings"]["h1_text"] == ["Hello Static"]
    assert res["text_content"]["visible_word_count"] > 0


@pytest.mark.asyncio
async def test_2_js_generated_content():
    """2. Test JavaScript dynamically generating content."""
    html = """<html><body>
        <div id="content"></div>
        <script>
            document.getElementById('content').innerHTML = '<p>Generated by JavaScript</p>';
        </script>
    </body></html>"""
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        context = await browser.new_context()
        page = await context.new_page()
        await page.route("https://example.com/js-content", lambda route: route.fulfill(status=200, body=html, content_type="text/html"))

        res = await analyze_rendered_page("https://example.com/js-content", options={"wait_after_load_ms": 100}, page_instance=page)
        await context.close()
        await browser.close()

    assert res["text_content"]["visible_word_count"] >= 3


def test_3_empty_application_shell():
    """3. Test empty application shell DOM parsing."""
    html = '<div id="root"></div>'
    parsed = parse_rendered_dom_structure(html, "https://example.com", "", "", "")
    assert "root" in parsed["application_roots"]
    assert parsed["content_status"]["possible_empty_rendered_page"] is True


def test_4_js_changes_body_text():
    """4. Test visible text structure parsing after dynamic change."""
    html = '<div><p>Updated Client Content</p></div>'
    parsed = parse_rendered_dom_structure(html, "https://example.com", "Updated Client Content", "", "")
    assert parsed["text_content"]["visible_character_count"] == len("Updated Client Content")


def test_5_js_generated_heading():
    """5. Test rendered H1 heading extraction."""
    html = '<main><h1>Dynamic Heading</h1></main>'
    parsed = parse_rendered_dom_structure(html, "https://example.com", "Dynamic Heading", "Dynamic Heading", "")
    assert parsed["headings"]["h1_count"] == 1
    assert parsed["headings"]["h1_text"] == ["Dynamic Heading"]


def test_6_js_generated_links():
    """6. Test rendered <a> links extraction."""
    html = '<div><a href="/prod/1">Product 1</a><a href="https://other.com">Other</a></div>'
    parsed = parse_rendered_dom_structure(html, "https://example.com", "", "", "")
    assert parsed["links"]["total"] == 2
    assert parsed["links"]["internal"] == 1
    assert parsed["links"]["external"] == 1


def test_7_js_generated_structured_data():
    """7. Test rendered JSON-LD extraction."""
    html = '<script type="application/ld+json">{"@context": "https://schema.org", "@type": "Product", "name": "Item"}</script>'
    parsed = parse_rendered_dom_structure(html, "https://example.com", "", "", "")
    assert parsed["structured_data"]["json_ld_blocks"] == 1
    assert "Product" in parsed["structured_data"]["types"]


def test_8_missing_title():
    """8. Test rendered document without title."""
    html = '<body><h1>No Title</h1></body>'
    parsed = parse_rendered_dom_structure(html, "https://example.com", "No Title", "", "")
    assert parsed["title"]["exists"] is False


def test_9_meta_description():
    """9. Test rendered meta description extraction."""
    html = '<meta name="description" content="Rendered page description">'
    parsed = parse_rendered_dom_structure(html, "https://example.com", "", "", "")
    assert parsed["meta_description"]["exists"] is True
    assert parsed["meta_description"]["content"] == "Rendered page description"


def test_10_canonical():
    """10. Test rendered canonical link tag."""
    html = '<link rel="canonical" href="https://example.com/canonical-item">'
    parsed = parse_rendered_dom_structure(html, "https://example.com/item", "", "", "")
    assert parsed["canonical"]["exists"] is True
    assert parsed["canonical"]["is_absolute"] is True


def test_11_language():
    """11. Test rendered language attribute."""
    html = '<html lang="fr"><head></head><body></body></html>'
    parsed = parse_rendered_dom_structure(html, "https://example.com", "", "", "")
    assert parsed["language"]["declared"] is True
    assert parsed["language"]["value"] == "fr"


def test_12_multiple_h1():
    """12. Test detection of multiple H1 tags in rendered DOM."""
    html = '<h1>Title 1</h1><h1>Title 2</h1>'
    parsed = parse_rendered_dom_structure(html, "https://example.com", "Title 1 Title 2", "", "")
    assert parsed["headings"]["h1_count"] == 2
    assert parsed["headings"]["multiple_h1"] is True


def test_13_image_extraction():
    """13. Test rendered <img> elements extraction."""
    html = '<img src="/photo.jpg" alt="A sample photo" width="500" height="300" loading="lazy">'
    parsed = parse_rendered_dom_structure(html, "https://example.com", "", "", "")
    assert parsed["images"]["count"] == 1
    assert parsed["images"]["missing_alt_count"] == 0
    assert parsed["images"]["images"][0]["alt"] == "A sample photo"


def test_14_missing_image_alt():
    """14. Test missing alt attribute on rendered image."""
    html = '<img src="/no-alt.jpg">'
    parsed = parse_rendered_dom_structure(html, "https://example.com", "", "", "")
    assert parsed["images"]["missing_alt_count"] == 1


def test_15_semantic_html():
    """15. Test rendered semantic HTML5 tags."""
    html = '<main><article><section></section></article><aside></aside></main><nav></nav>'
    parsed = parse_rendered_dom_structure(html, "https://example.com", "", "", "")
    sem = parsed["semantic_structure"]
    assert sem["main"] == 1
    assert sem["article"] == 1
    assert sem["section"] == 1
    assert sem["nav"] == 1
    assert sem["aside"] == 1


def test_16_robots_meta():
    """16. Test rendered meta robots tag."""
    html = '<meta name="robots" content="noindex, nofollow">'
    parsed = parse_rendered_dom_structure(html, "https://example.com", "", "", "")
    assert parsed["robots_meta"]["exists"] is True
    assert "noindex" in parsed["robots_meta"]["directives"]


@pytest.mark.asyncio
async def test_17_x_robots_tag_header():
    """17. Test X-Robots-Tag captured from navigation headers."""
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        context = await browser.new_context()
        page = await context.new_page()

        html = "<html><body><h1>Hello</h1></body></html>"
        headers = {"x-robots-tag": "nosnippet, noarchive"}
        await page.route("https://example.com/x-robots", lambda route: route.fulfill(status=200, body=html, headers=headers, content_type="text/html"))

        res = await analyze_rendered_page("https://example.com/x-robots", options={"wait_after_load_ms": 0}, page_instance=page)
        await context.close()
        await browser.close()

    assert res["robots_headers"]["x_robots_tag"] == "nosnippet, noarchive"


@pytest.mark.asyncio
async def test_18_js_error_capture():
    """18. Test browser capturing unhandled JavaScript runtime error."""
    html = """<html><body>
        <h1>Error Page</h1>
        <script>
            throw new Error("Simulated JS crash");
        </script>
    </body></html>"""
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        context = await browser.new_context()
        page = await context.new_page()
        await page.route("https://example.com/js-err", lambda route: route.fulfill(status=200, body=html, content_type="text/html"))

        res = await analyze_rendered_page("https://example.com/js-err", options={"wait_after_load_ms": 100}, page_instance=page)
        await context.close()
        await browser.close()

    assert res["javascript"]["error_count"] >= 1
    assert "Simulated JS crash" in res["javascript"]["errors"][0]["message"]


@pytest.mark.asyncio
async def test_19_console_error_capture():
    """19. Test console.error capturing."""
    html = """<html><body>
        <script>
            console.error("Test console error message");
            console.warn("Test console warning message");
        </script>
    </body></html>"""
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        context = await browser.new_context()
        page = await context.new_page()
        await page.route("https://example.com/console-test", lambda route: route.fulfill(status=200, body=html, content_type="text/html"))

        res = await analyze_rendered_page("https://example.com/console-test", options={"wait_after_load_ms": 100}, page_instance=page)
        await context.close()
        await browser.close()

    assert res["console"]["error_count"] >= 1
    assert res["console"]["warning_count"] >= 1


@pytest.mark.asyncio
async def test_20_failed_resource_capture():
    """20. Test capturing failed network resource request."""
    html = '<html><head><script src="https://example.com/missing-bundle.js"></script></head><body><h1>Hi</h1></body></html>'
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        context = await browser.new_context()
        page = await context.new_page()

        await page.route("https://example.com/res-fail", lambda route: route.fulfill(status=200, body=html, content_type="text/html"))
        await page.route("https://example.com/missing-bundle.js", lambda route: route.abort("failed"))

        res = await analyze_rendered_page("https://example.com/res-fail", options={"wait_after_load_ms": 100}, page_instance=page)
        await context.close()
        await browser.close()

    assert res["resources"]["failed_count"] >= 1


@pytest.mark.asyncio
async def test_21_navigation_timeout_fallback():
    """21. Test handling of navigation timeout with partial DOM extraction."""
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        context = await browser.new_context()
        page = await context.new_page()

        async def slow_route(route):
            await asyncio.sleep(0.5)
            await route.fulfill(status=200, body="<html><body>Slow</body></html>", content_type="text/html")

        await page.route("https://example.com/slow", slow_route)

        res = await analyze_rendered_page("https://example.com/slow", options={"navigation_timeout_ms": 100}, page_instance=page)
        await context.close()
        await browser.close()

    assert res["rendering"]["status"] in ("partial", "browser_error", "navigation_error")


def test_22_malformed_html():
    """22. Test parsing malformed rendered HTML."""
    html = '<div><p>Unclosed paragraph<h1>Heading without body'
    parsed = parse_rendered_dom_structure(html, "https://example.com", "Unclosed paragraph Heading without body", "", "")
    assert parsed["headings"]["h1_count"] == 1


def test_23_relative_links():
    """23. Test relative links in rendered DOM."""
    html = '<a href="/catalog/shoes">Shoes</a>'
    parsed = parse_rendered_dom_structure(html, "https://example.com/store", "", "", "")
    assert parsed["links"]["relative"] == 1
    assert parsed["links"]["internal"] == 1


def test_24_external_links():
    """24. Test external links in rendered DOM."""
    html = '<a href="https://google.com">Search</a>'
    parsed = parse_rendered_dom_structure(html, "https://example.com", "", "", "")
    assert parsed["links"]["external"] == 1


def test_25_fragment_links():
    """25. Test fragment links in rendered DOM."""
    html = '<a href="#top">Back to top</a>'
    parsed = parse_rendered_dom_structure(html, "https://example.com", "", "", "")
    assert parsed["links"]["fragment_only"] == 1


def test_26_application_root_detection():
    """26. Test detecting various SPA application roots."""
    html = '<div id="__next"><div data-reactroot="">Content</div></div>'
    parsed = parse_rendered_dom_structure(html, "https://example.com", "Content", "", "")
    assert "__next" in parsed["application_roots"] or "data-reactroot" in parsed["application_roots"]
    assert parsed["client_rendering"]["application_root_detected"] is True


def test_27_empty_rendered_page():
    """27. Test empty rendered page detection."""
    html = '<body><div id="root"></div></body>'
    parsed = parse_rendered_dom_structure(html, "https://example.com", "", "", "")
    assert parsed["content_status"]["possible_empty_rendered_page"] is True
    assert parsed["content_status"]["meaningful_content_available"] is False


def test_28_dom_size_limit():
    """28. Test DOM size limit truncation."""
    huge_html = "<div>" + "<p>Sample text</p>" * 200 + "</div>"
    parsed = parse_rendered_dom_structure(huge_html, "https://example.com", "Sample text", "", "", max_dom_size_bytes=500)
    assert parsed["dom"]["truncated"] is True


@pytest.mark.asyncio
async def test_29_redirect_handling():
    """29. Test client-side or server-side navigation redirect tracking."""
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        context = await browser.new_context()
        page = await context.new_page()

        # Handle redirect in Chromium
        await page.route("https://example.com/initial", lambda route: route.fulfill(status=302, headers={"Location": "https://example.com/dest"}))
        await page.route("https://example.com/dest", lambda route: route.fulfill(status=200, body="<html><body>Destination</body></html>", content_type="text/html"))

        res = await analyze_rendered_page("https://example.com/initial", options={"wait_after_load_ms": 0}, page_instance=page)
        await context.close()
        await browser.close()

    assert res["navigation"]["final_url"] in ("https://example.com/dest", "https://example.com/initial")


@pytest.mark.asyncio
async def test_30_unsafe_ssrf_url_rejection():
    """30. Test rejection of unsafe localhost / private IP targets."""
    res = await analyze_rendered_page("http://127.0.0.1:8000/admin")
    assert res["rendering"]["status"] == "navigation_error"
    assert res["errors"][0]["type"] == "security_error"

    res_localhost = await analyze_rendered_page("http://localhost:3000")
    assert res_localhost["rendering"]["status"] == "navigation_error"


@pytest.mark.asyncio
async def test_31_browser_launch_failure_handling():
    """31. Test that launch errors (e.g. missing Chromium binary) result in browser_launch_failure status."""
    from unittest.mock import AsyncMock, patch

    mock_playwright_ctx = AsyncMock()
    mock_playwright_ctx.chromium.launch.side_effect = Exception("Executable doesn't exist at /root/.cache/ms-playwright/chromium/chrome")

    with patch("render_analyzer.async_playwright") as mock_pw_factory:
        mock_pw_factory.return_value.start = AsyncMock(return_value=mock_playwright_ctx)
        res = await analyze_rendered_page("https://example.com")

    assert res["rendering"]["status"] == "browser_launch_failure"
    assert len(res["errors"]) == 1
    assert res["errors"][0]["type"] == "launch_error"
    assert "Executable doesn't exist" in res["errors"][0]["message"]


@pytest.mark.asyncio
async def test_32_browser_render_crash_handling():
    """32. Test that mid-render crashes result in browser_error status."""
    from unittest.mock import AsyncMock, MagicMock

    mock_page = MagicMock()
    mock_page.goto = AsyncMock(side_effect=Exception("Page crashed: Target crashed while loading JS bundle"))

    res = await analyze_rendered_page("https://example.com", page_instance=mock_page)

    assert res["rendering"]["status"] == "browser_error"
    assert len(res["errors"]) == 1
    assert res["errors"][0]["type"] == "render_error"
    assert "Page crashed" in res["errors"][0]["message"]

